# Update World Football Portal Dashboard data
name: update-world-football-data

on:
  schedule:
    - cron: '00 23 * * *'
  workflow_dispatch:

jobs:
  run-r-script:
    name: Run R script and update Google Sheets
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install libcurl and libssl on Linux
        run: 'sudo apt-get -y install libcurl4-openssl-dev'
        shell: bash
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("tidyverse", "googledrive", "googlesheets4"))'
      - name: Run All Leagues script
        run: |
          source('All-Leagues-Tableau-Script.R')
        shell: Rscript {0}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data 
          git commit -m 'Run script and update Google Sheet with latest matches' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
