on:
  schedule:
    - cron:  "00 23 * * *" # Every day at 11:00pm UTC (4:00pm Pacific)'
  workflow_dispatch:

name: scripts

jobs:
  run-r-script:
    runs-on: ubuntu-latest # use Ubuntu
    env:
      # The GitHub token will be available 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
    steps:
      # imports an action from another repository, 
      # that enables the machine
      # to access the code inside our repository
      - uses: actions/checkout@v3 
      # imports an action from another repository, 
      # that installs R on the machine
      - uses: r-lib/actions/setup-r@v2
        with:
          # uses the RStudio Package Manager
          use-public-rspm: true
          
          # Set-up R
      - name: Install packages
        run: |
          R -e 'install.packages("tidyverse")'
          R -e 'install.packages("googlesheets4")'

      - name: Execute Script
        # executes the RScript stored in the file
        # scripts/All Leagues Tableau Script.R
        run: |
          Rscript "scripts/All Leagues Tableau Script.R"

        # save the results in the repository
        # using git in the command line
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Results from R script" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
